@startuml
class Beskrivelse {
    +tekstInnhold: string
    +tekstFormat: TekstFormat
}

Beskrivelse -- TekstFormat

class TekstFormat <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml