@startuml
!include ../no.ks.fiks.politisk.behandling.v1.felles.eksternnoekkel/schema.puml
!include ../no.ks.fiks.politisk.behandling.v1.felles.saksnummer/schema.puml
!include ../no.ks.fiks.politisk.behandling.v1.felles.beskrivelse/schema.puml
!include ../no.ks.fiks.politisk.behandling.v1.felles.skjerming/schema.puml
!include ../no.ks.fiks.politisk.behandling.v1.felles.moete/schema.puml

class SendUtvalgssakerEinnsyn {
    +moete: Moete
    +utvalg: Utvalg
    +avsender: Avsender
    +sak: Utvalgssakeinnsyn[]
}

SendUtvalgssakerEinnsyn -- Moete
SendUtvalgssakerEinnsyn -- Utvalg
SendUtvalgssakerEinnsyn -- Avsender
SendUtvalgssakerEinnsyn -- Utvalgssakeinnsyn

class Utvalg {
    +utvalgId: string
    +utvalgNavn: string
    +moete: Moete[]
    +medlem: Utvalgsmedlem[]
}

Utvalg -- Utvalgsmedlem

class Avsender {
    +organisasjonsnummer: string
    +kommunenummer: string
    +navn: string
}

class Utvalgssakeinnsyn {
    +referanseEksternNoekkel: EksternNoekkel
    +utvalgetsSaksnummer: Saksnummer
    +tittel: string
    +saksbeskrivelse: Saksbeskrivelse
    +forslagTilVedtak: Beskrivelse
    +skjerming: Skjerming
    +saksansvarlig: string
    +posisjon: object
}

Utvalgssakeinnsyn -- EksternNoekkel
Utvalgssakeinnsyn -- Saksnummer
Utvalgssakeinnsyn -- Saksbeskrivelse
Utvalgssakeinnsyn -- Beskrivelse
Utvalgssakeinnsyn -- Skjerming

class Saksbeskrivelse {
    +tekstInnhold: string
    +tekstFormat: SaksbeskrivelseTekstFormat
}

Saksbeskrivelse -- SaksbeskrivelseTekstFormat

class SaksbeskrivelseTekstFormat <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Utvalgsmedlem {
    +medlemsId: string
    +navn: string
    +rekkefoelge: integer
    +representerer: string
    +funksjon: string
    +fraDato: string
    +tilDato: string
    +epost: string
}

@enduml
