@startuml
participant Fagsystem as "Fagsystem"
participant Møtesystem as "Møtesystem"

Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.einnsyn.utvalgssaker.send
Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.mottatt

note left of Fagsystem
Dette viser meldingsutveksling
ved "e-innsyn send utvalgssaker" hvor 
mottat-melding skal sendes tilbake.
Mottatt-melding har ikke payload.
**Merk:** diagram er forenklet uten
Fiks-Protokoll som meldingskø
mellom Fagsystem og Møtesystem
end note

@enduml