@startuml
participant Fagsystem as "Fagsystem"
participant Møtesystem as "Møtesystem"

Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalg.hent
Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.feilmelding.ikkefunnet

note left of Fagsystem
Feilmelding **ikkefunnet**:
Dette viser meldingsutveksling
ved "hent utvalg" hvor det som 
blir etterspurt ikke eksisterer.
**Merk:** diagram er forenklet uten
Fiks-Protokoll som meldingskø
mellom Fagsystem og Møtesystem
end note

@enduml