@startuml
participant Møtesystem as "Møtesystem"
participant Fagsystem as "Fagsystem"
participant Arkivsystem as "Fiks-Arkiv arkivsystem"

Møtesystem -> Arkivsystem : Arkiver vedtak fra utvalg
Møtesystem -> Fagsystem : no.ks.fiks.politisk.behandling.v1.vedtakfrautvalg.send
Møtesystem <- Fagsystem : no.ks.fiks.politisk.behandling.v1.mottatt

note left of Møtesystem
Dette viser meldingsutveksling
ved "Send vedtak fra utvalg" hvor 
mottat-melding skal sendes tilbake.
Mottatt-melding har ikke payload.
**Merk:** diagram er forenklet uten
Fiks-Protokoll som meldingskø
mellom Fagsystem og Møtesystem
end note

@enduml