@startuml
!include ../no.ks.fiks.politisk.behandling.v1.felles.eksternnoekkel/schema.puml
!include ../no.ks.fiks.politisk.behandling.v1.felles.saksnummer/schema.puml
!include ../no.ks.fiks.politisk.behandling.v1.felles.skjerming/schema.puml
!include ../no.ks.fiks.politisk.behandling.v1.felles.journalnummer/schema.puml

class SendOrienteringssak {
    +sak: Sak
    +forslagTilBehandlingsplan: Behandlingsplan[]
}

SendOrienteringssak -- Sak
SendOrienteringssak -- Behandlingsplan

class Sak {
    +referanseEksternNoekkel: EksternNoekkel
    +fagsystemetsSaksnummer: Saksnummer
    +fagsystemetsReferanseEksternNoekkel: EksternNoekkel
    +tittel: string
    +saksbeskrivelse: Saksbeskrivelse
    +skjerming: Skjerming
    +saksansvarlig: string
    +posisjon: object
    +referanseForelderMappeEksternNoekkel: EksternNoekkel
    +arkivSaksnummer: Saksnummer
    +referanseRegistreringEksternNoekkel: EksternNoekkel
    +arkivJournalnummer: Journalnummer
    +arkivJournalpostnummer: integer
}

Sak -- EksternNoekkel
Sak -- Saksnummer
Sak -- Saksbeskrivelse
Sak -- Skjerming
Sak -- Journalnummer

class Saksbeskrivelse {
    +tekstInnhold: string
    +tekstFormat: SaksbeskrivelseTekstFormat
}

Saksbeskrivelse -- SaksbeskrivelseTekstFormat

class SaksbeskrivelseTekstFormat <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Behandlingsplan {
    +tilUtvalgId: string
    +tilUtvalgNavn: string
    +tilMoeteId: string
    +tilMoetedato: string
    +rekkefoelge: integer
}

@enduml
