@startuml
participant Fagsystem as "Fagsystem"
participant Møtesystem as "Møtesystem"
participant Arkivsystem as "Fiks-Arkiv arkivsystem"

Fagsystem -> Arkivsystem : Arkiver orienteringssak
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.orienteringssak.send
Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.feilmelding.ugyldigforespoersel

note left of Fagsystem
Feilmelding **ugyldigforespoersel**:
Dette viser meldingsutveksling ved
"send orienteringssak" hvor meldingen
som kommer fra fagsystem er ugyldig.
**Merk:** diagram er forenklet uten
Fiks-Protokoll som meldingskø
mellom Fagsystem og Møtesystem
end note

@enduml