@startuml
skinparam sequenceMessageAlign center 
skinparam BoxPadding 10
skinparam ParticipantPadding 10

title "Send utvalgssak sammen med send vedtak fra utvalg\n2 arkivsystem"

box "Fagsystem" #LightBlue
participant Arkivsystem [
    = Arkivsystem
    ----
    Fagsystemets arkivsystem
    ]
participant Fagsystem [ 
    = Fagsystem
    ]
end box
box "Møtesystem" #LightBlue
participant Møtesystem [
    = Møtesystem
    ]
participant Arkivsystem2 [
    = Arkivsystem
    ----
    Møtesystemets arkivsystem
    ]
end box

Fagsystem -> Arkivsystem : Fagsystem arkiverer utvalgssak

...møtesystem oppretter sak? ...

Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.send
Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.mottatt

...Møter og behandlingsplan blir laget...
...Hele behandlingsplan blir alltid sendt (ikke arkiveres)...

Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.behandlingsplan.send
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.mottatt


...Utvalg(ene) har gjort en oppdatering på saksframlegg...

Møtesystem -> Arkivsystem2 : Møtesystem arkiverer saksframlegg fra utvalg
Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.saksframlegg.send
Fagsystem -> Arkivsystem : Arkiver saksframlegg fra utvalg
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.saksframlegg.send.kvittering


...Utvalg(ene) har gjort en oppdatering på behandlingsplan (ikke arkiveres)...

Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.behandlingsplan.send
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.mottatt




...1 av utvalgene har en ferdig innstilling...

Møtesystem -> Arkivsystem2 : Møtesystem arkiverer 1 vedtak fra utvalg
Møtesystem -> Fagsystem : no.ks.fiks.politisk.behandling.v1.vedtakfrautvalg.send
Fagsystem -> Arkivsystem : Fagsystem arkiverer 1 vedtak fra utvalg
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.vedtakfrautvalg.send.kvittering


...Utvalg(ene) har utarbeidet et ferdig vedtak (flagg for endelig)...

Møtesystem -> Arkivsystem2 : Møtesystem arkiverer endelig vedtak fra utvalg
Møtesystem -> Fagsystem : no.ks.fiks.politisk.behandling.v1.vedtakfrautvalg.send
Fagsystem -> Arkivsystem : Fagsystem arkiverer endelig vedtak fra utvalg
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.vedtakfrautvalg.send.kvittering

note right of Fagsystem
Diagrammet viser mulig meldingsflyt
der hvor det er 2 arkivsystem,
et for Fagsystem og et for Møtesystem
end note

@enduml