@startuml
title "Send utvalgssak sammen med send vedtak fra utvalg"

participant Arkivsystem as "Felles arkivsystem"
participant Fagsystem as "Fagsystem"
participant Møtesystem as "Møtesystem"

Fagsystem -> Arkivsystem : Fagsystem arkiverer utvalgssak

...møtesystem oppretter sak? ...

Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.send
Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.mottatt

...Møter og behandlingsplan blir laget...
...Hele behandlingsplan blir alltid sendt (ikke arkiveres)...

Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.behandlingsplan.send
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.mottatt


...Utvalg(ene) har gjort en oppdatering på saksframlegg...

Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.saksframlegg.send
Fagsystem -> Arkivsystem : Arkiver saksframlegg fra utvalg
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.saksframlegg.send.kvittering


...Utvalg(ene) har gjort en oppdatering på behandlingsplan (ikke arkiveres)...

Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalgssak.behandlingsplan.send
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.mottatt




...1 av utvalgene har en ferdig innstilling...


Møtesystem -> Fagsystem : no.ks.fiks.politisk.behandling.v1.vedtakfrautvalg.send
Fagsystem -> Arkivsystem : Fagsystem arkiverer 1 vedtak fra utvalg
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.vedtakfrautvalg.send.kvittering


...Utvalg(ene) har utarbeidet et ferdig vedtak (flagg for endelig)...


Møtesystem -> Fagsystem : no.ks.fiks.politisk.behandling.v1.vedtakfrautvalg.send
Fagsystem -> Arkivsystem : Fagsystem arkiverer endelig vedtak fra utvalg
Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.vedtakfrautvalg.send.kvittering

note right of Fagsystem
Diagrammet viser mulig meldingsflyt
der hvor det er felles arkivsystem
end note

@enduml