@startuml
participant Fagsystem as "Fagsystem"
participant Møtesystem as "Møtesystem"

Fagsystem -> Møtesystem : no.ks.fiks.politisk.behandling.v1.utvalg.hent
Fagsystem <- Møtesystem : no.ks.fiks.politisk.behandling.v1.feilmelding.serverfeil

note left of Fagsystem
Feilmelding **serverfeil**:
Dette viser meldingsutveksling ved
"send delegertvedtak" hvor møtesystem
feiler og ikke kan levere et svar
**Merk:** diagram er forenklet uten
Fiks-Protokoll som meldingskø
mellom Fagsystem og Møtesystem
end note

@enduml