@startuml
participant Møtesystem as "Møtesystem"
participant EInnsyn as "E-Innsyn"

Møtesystem -> EInnsyn : no.ks.fiks.politisk.behandling.v1.einnsyn.vedtak.send
Møtesystem <- EInnsyn : no.ks.fiks.politisk.behandling.v1.feilmelding.serverfeil

note left of Møtesystem
Feilmelding **serverfeil**:
Dette viser meldingsutveksling ved
"e-innsyn send vedtak" hvor møtesystem
feiler og ikke kan levere et svar.
**Merk:** diagram er forenklet uten
Fiks-Protokoll som meldingskø
mellom Fagsystem og Møtesystem
end note

@enduml